
# デバッグログをコンソールに出力する
enable-debug: false

# 置換するアイテム
items:
  - old: "mythicmobs:OldItemTypeName" # 置換元
    new: "mythicmobs:NewItemTypeName"  # 置換先 (省略可)
  - "mythicmobs:OldItemTypeName2"  # 削除のみ (短縮)
