
# デバッグログをコンソールに出力する
enable-debug: false

# 置換するアイテムの設定
#   アイテムの指定
#     "(タイプ):(アイテム)"
#     タイプにはプラグイン名が入り、アイテムにはアイテムを識別するIDや名前を指定します。
#     対応しているタイプは mythicmobs, mmoitems, itemsadder です。
#   置換する新しいアイテムを指定する new 項目を省略することで削除のみ実行できます。
items:
  - old: "mythicmobs:OldItemTypeName" # 回収対象のアイテム
    new: "mythicmobs:NewItemTypeName"  # 置換する新しいアイテム (省略可)
  - "mmoitems:ITEM_TYPE:ITEM_ID"  # 回収対象のアイテム。削除のみ (短縮)
  - "itemsadder:namespace:itemid"
