name: ItemRecall
version: '${version}'
main: com.gmail.necnionch.myplugin.itemrecall.bukkit.ItemRecallPlugin
api-version: '1.13'
author: Necnion8
website: https://github.com/Necnion8/ItemRecall
description: "回収対応になったアイテムを削除、または置換するプラグイン"

softdepend:
  - MythicMobs
  - MMOItems

permissions:
  itemrecall.admin:
    default: op
    children:
      - itemrecall.bypass

  itemrecall.bypass:
    default: false
    description: "この権限を持っている人は、対象のアイテムを処理しません"
